// Database types for Supabase
// This file will be auto-generated by Supabase CLI in production
// For now, we define basic structure manually

export interface Database {
  public: {
    Tables: {
      blueprints: {
        Row: Blueprint
        Insert: Omit<Blueprint, 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Omit<Blueprint, 'id' | 'created_at'>>
      }
      submissions: {
        Row: Submission
        Insert: Omit<Submission, 'id' | 'created_at'>
        Update: Partial<Omit<Submission, 'id' | 'created_at'>>
      }
      saved_blueprints: {
        Row: SavedBlueprint
        Insert: Omit<SavedBlueprint, 'id' | 'created_at'>
        Update: Partial<Omit<SavedBlueprint, 'id'>>
      }
      profiles: {
        Row: UserProfile
        Insert: Omit<UserProfile, 'created_at' | 'updated_at'>
        Update: Partial<Omit<UserProfile, 'id' | 'created_at'>>
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      difficulty_level: 'beginner' | 'intermediate' | 'advanced'
      submission_status: 'pending' | 'approved' | 'rejected'
    }
  }
}

interface Blueprint {
  id: string
  title: string
  description: string
  category: string
  difficulty: 'beginner' | 'intermediate' | 'advanced'
  duration: string
  materials: string[]
  tools: string[]
  steps: Step[]
  science_explanation?: string
  safety_notes?: string[]
  image_url?: string
  video_url?: string
  author_id?: string
  status: 'draft' | 'published'
  views: number
  likes: number
  created_at: string
  updated_at: string
}

interface Step {
  number: number
  title: string
  description: string
  image_url?: string
  tips?: string
}

interface Submission {
  id: string
  title: string
  description: string
  category: string
  difficulty: 'beginner' | 'intermediate' | 'advanced'
  materials: string[]
  submitter_name: string
  submitter_email: string
  status: 'pending' | 'approved' | 'rejected'
  admin_notes?: string
  created_at: string
  reviewed_at?: string
}

interface SavedBlueprint {
  id: string
  user_id: string
  blueprint_id: string
  created_at: string
}

interface UserProfile {
  id: string
  email: string
  display_name?: string
  avatar_url?: string
  bio?: string
  created_at: string
  updated_at: string
}

export type { Blueprint, Step, Submission, SavedBlueprint, UserProfile }
